### ISSUE TITLE
您好,请问怎么拿到展示得礼物在第几条跑道?

### ISSUE THREAD

**Issue by oooo7777777** [Yuphee/RewardLayout#8]
您好,请问怎么拿到展示得礼物在第几条跑道?

**Comment by Yuphee** [comment]
目前没有这个标记




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yuphee/RewardLayout"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 下午4:49
收件人:&nbsp;"Yuphee/RewardLayout"<RewardLayout@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Yuphee/RewardLayout] 您好,请问怎么拿到展示得礼物在第几条跑道? (#8)





 
您好,请问怎么拿到展示得礼物在第几条跑道?

**Comment by oooo7777777** [comment]
> 目前没有这个标记
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Yuphee/RewardLayout" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月6日(星期四) 下午4:49 收件人:&nbsp;"Yuphee/RewardLayout"<RewardLayout@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[Yuphee/RewardLayout] 您好,请问怎么拿到展示得礼物在第几条跑道? (#8) 您好,请问怎么拿到展示得礼物在第几条跑道? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

能给我指点下在哪里改吗?

**Comment by Yuphee** [comment]
addChildGift



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yuphee/RewardLayout"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 晚上6:03
收件人:&nbsp;"Yuphee/RewardLayout"<RewardLayout@noreply.github.com&gt;;
抄送:&nbsp;"张越峰"<437220638@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Yuphee/RewardLayout] 您好,请问怎么拿到展示得礼物在第几条跑道? (#8)





  
目前没有这个标记
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Yuphee/RewardLayout" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月6日(星期四) 下午4:49 收件人:&nbsp;"Yuphee/RewardLayout"<RewardLayout@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[Yuphee/RewardLayout] 您好,请问怎么拿到展示得礼物在第几条跑道? (#8) 您好,请问怎么拿到展示得礼物在第几条跑道? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
能给我指点下在哪里改吗?
